version: "3"
services:
    node-app:
      build: 
        context: ./
        args:
          NODE_ENV: development
      ports: 
        - 4000:3000
      volumes:
        - ./:/app
        - /app/node_modules
      environment:
        - NODE_ENV=development
      env_file:
        - ./.env
      command: npm run dev 
