version: "3"
services:
    node-app:
      build: 
        context: ./
        args:
          NODE_ENV: production
      ports: 
        - 5000:3000
      env_file:
        - ./.env
      environment:
        - NODE_ENV=production
      command: node ./bin/www
