version: "3"
services:
    node-app:
      build: ./
      env_file:
        - ./.env
      depends_on :
        - mongo
    mongo:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
